name: Deploy Questions

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7

    - name: Prepare
      run: |
        git clone https://github.com/gurukulams/design-system.git design-system
        cp design-system/package-lock.json .
        cd design-system
        rm package-lock.json
        cp -rf ../questions questions

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Build
      run: |
        cd design-system
        npm i
        npm run build:questions

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: design-system/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4