# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  call-workflow:
    # You must add these permissions so the called workflow can deploy
    permissions:
      contents: read
      id-token: write
      pages: write      # Required if deploying to GitHub Pages
    uses: gurukulams/workshop/.github/workflows/build-question-repo.yml@main
    secrets: inherit # If the sub-workflow needs access to secrets

  build:
    runs-on: ubuntu-latest
  # Deployment job
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.QUESTION_REPO_HOST }}
        username: ${{ secrets.QUESTION_REPO_USER }}
        key: ${{ secrets.QUESTION_REPO_KEY }}
        target: ${{ secrets.QUESTION_REPO_WORKSHOP_ROOT }}
        source: "design-system/dist"
        strip_components: 2