name: Deploy Questions

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: gurukulams/workshop/.github/workflows/build-question-repo.yml@main
    secrets: inherit

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4